[language-server.efm]
command = "efm-langserver"

[[language]]
name = "typescript"
language-servers = [
  { name = "efm", only-features = [ "diagnostics", "format" ] },
  { name = "typescript-language-server", except-features = [ "format" ] }
]

[[language]]
name = "markdown"
auto-format = true
language-servers = [
  { name = "efm", only-features = [ "diagnostics", "format" ] },
]

